# site settings
title: iCyPhy
subtitle: Industrial Cyber-Physical Systems Center
email: youremailaddress@gmail.com
description: Pre-competitive research on architectures and design,<br/> modeling, and analysis techniques for cyber-physical systems,<br/> with emphasis on industrial applications.
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 545 Cory Hall
city: Berkeley
state: CA
zip_code: 94720
country: USA
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/icyphy
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url: https://icyphy.slack.com
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
